env:
  CIRRUS_CLONE_DEPTH: 1

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y gmake
  script:
    env PATH=/usr/local/bin:$PATH gmake -C src profile-build ARCH=x86-64-bmi2 COMP=clang

